apiVersion: v1
kind: Namespace
metadata:
  name: virt-demo
  labels:
    # This label grants the GitOps application controller permission to manage resources in this namespace
    argocd.argoproj.io/managed-by: openshift-gitops
