apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: vm-managed-clusters
  namespace: openshift-gitops
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
      tolerationSeconds: 600
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
      tolerationSeconds: 600
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: "In"
              values:
                - OpenShift
            - key: name
              operator: NotIn
              values:
                - local-cluster
